/* Generated by Yosys 0.9+932 (git sha1 65f197e2, clang  -fPIC -Os) */

(* top =  1  *)
(* src = "AND2.v:1" *)
module AND2(a, b, o);
  (* src = "AND2.v:2" *)
  input a;
  (* src = "AND2.v:3" *)
  input b;
  (* src = "AND2.v:4" *)
  output o;
  assign o = a &(* src = "AND2.v:7" *)  b;
endmodule
