/* Generated by Yosys 0.9+932 (git sha1 65f197e2, clang  -fPIC -Os) */

(* top =  1  *)
(* src = "AND3.v:1" *)
module AND3(a, b, c, o);
  (* src = "AND3.v:8" *)
  wire _0_;
  (* src = "AND3.v:2" *)
  input a;
  (* src = "AND3.v:3" *)
  input b;
  (* src = "AND3.v:4" *)
  input c;
  (* src = "AND3.v:5" *)
  output o;
  assign _0_ = a &(* src = "AND3.v:8" *)  b;
  assign o = _0_ &(* src = "AND3.v:8" *)  c;
endmodule
