/* Generated by Yosys 0.9+932 (git sha1 65f197e2, clang  -fPIC -Os) */

(* top =  1  *)
(* src = "elevator_fsm.sv:2" *)
module elevator_fsm(clk, rst, door_open_req, door_close_req, car_floor_req, floor_1_cab_req, floor_2_cab_req, floor_sensor, cmd_door_open, cmd_door_close, cmd_car_up, cmd_car_down);
  (* src = "elevator_fsm.sv:67" *)
  wire _000_;
  (* src = "elevator_fsm.sv:67" *)
  wire _001_;
  (* src = "elevator_fsm.sv:67" *)
  wire _002_;
  (* src = "elevator_fsm.sv:67" *)
  wire _003_;
  (* src = "elevator_fsm.sv:24" *)
  wire [7:0] _004_;
  (* src = "elevator_fsm.sv:33" *)
  wire [3:0] _005_;
  (* src = "elevator_fsm.sv:24" *)
  wire [3:0] _006_;
  (* src = "elevator_fsm.sv:67" *)
  wire [7:0] _007_;
  (* src = "elevator_fsm.sv:33" *)
  wire [3:0] _008_;
  (* src = "elevator_fsm.sv:33" *)
  wire [3:0] _009_;
  (* src = "elevator_fsm.sv:33" *)
  wire [3:0] _010_;
  (* src = "elevator_fsm.sv:33" *)
  wire [3:0] _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire [15:0] _021_;
  wire [7:0] _022_;
  wire [3:0] _023_;
  wire [1:0] _024_;
  wire [1:0] _025_;
  wire [1:0] _026_;
  wire [1:0] _027_;
  wire [1:0] _028_;
  wire [1:0] _029_;
  wire [1:0] _030_;
  wire [1:0] _031_;
  wire [1:0] _032_;
  wire [1:0] _033_;
  wire [1:0] _034_;
  wire [1:0] _035_;
  wire [1:0] _036_;
  wire [1:0] _037_;
  wire [1:0] _038_;
  wire [1:0] _039_;
  wire [1:0] _040_;
  wire [1:0] _041_;
  wire [1:0] _042_;
  wire [1:0] _043_;
  wire [1:0] _044_;
  wire [1:0] _045_;
  wire [1:0] _046_;
  wire [1:0] _047_;
  wire [1:0] _048_;
  wire [1:0] _049_;
  wire [1:0] _050_;
  wire [1:0] _051_;
  wire [1:0] _052_;
  wire [1:0] _053_;
  wire [1:0] _054_;
  wire [1:0] _055_;
  wire [1:0] _056_;
  wire [1:0] _057_;
  wire [1:0] _058_;
  wire [1:0] _059_;
  wire [1:0] _060_;
  wire [1:0] _061_;
  wire [1:0] _062_;
  wire [1:0] _063_;
  wire [31:0] _064_;
  wire [3:0] _065_;
  wire [3:0] _066_;
  wire [3:0] _067_;
  wire [3:0] _068_;
  wire [3:0] _069_;
  wire [3:0] _070_;
  wire [3:0] _071_;
  wire [3:0] _072_;
  wire [3:0] _073_;
  wire [3:0] _074_;
  wire [3:0] _075_;
  wire [3:0] _076_;
  wire [3:0] _077_;
  wire [3:0] _078_;
  wire [3:0] _079_;
  wire [3:0] _080_;
  wire [3:0] _081_;
  wire [3:0] _082_;
  wire [3:0] _083_;
  wire [3:0] _084_;
  wire [3:0] _085_;
  wire [3:0] _086_;
  wire [3:0] _087_;
  wire [3:0] _088_;
  wire [3:0] _089_;
  wire [3:0] _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  wire _107_;
  wire _108_;
  wire _109_;
  wire _110_;
  wire _111_;
  wire _112_;
  wire _113_;
  wire _114_;
  wire _115_;
  wire _116_;
  wire _117_;
  (* src = "elevator_fsm.sv:55" *)
  wire _118_;
  (* src = "elevator_fsm.sv:25" *)
  wire _119_;
  wire _120_;
  (* src = "elevator_fsm.sv:89|elevator_fsm.sv:68|<techmap.v>:432" *)
  wire [3:0] _121_;
  (* src = "elevator_fsm.sv:89|elevator_fsm.sv:68|<techmap.v>:428" *)
  wire _122_;
  wire _123_;
  wire _124_;
  wire _125_;
  wire _126_;
  (* src = "elevator_fsm.sv:89|elevator_fsm.sv:68|<techmap.v>:432" *)
  wire [3:0] _127_;
  (* src = "elevator_fsm.sv:89|elevator_fsm.sv:68|<techmap.v>:428" *)
  wire _128_;
  wire _129_;
  wire _130_;
  wire _131_;
  wire _132_;
  (* src = "elevator_fsm.sv:89|elevator_fsm.sv:68|<techmap.v>:432" *)
  wire [3:0] _133_;
  (* src = "elevator_fsm.sv:89|elevator_fsm.sv:68|<techmap.v>:428" *)
  wire _134_;
  wire _135_;
  wire _136_;
  wire _137_;
  wire _138_;
  (* src = "elevator_fsm.sv:89|elevator_fsm.sv:68|<techmap.v>:432" *)
  wire [3:0] _139_;
  (* src = "elevator_fsm.sv:89|elevator_fsm.sv:68|<techmap.v>:428" *)
  wire _140_;
  wire _141_;
  wire _142_;
  wire _143_;
  wire _144_;
  wire [3:0] _145_;
  wire _146_;
  wire [3:0] _147_;
  wire _148_;
  wire [3:0] _149_;
  wire [3:0] _150_;
  wire _151_;
  wire [3:0] _152_;
  wire _153_;
  (* src = "elevator_fsm.sv:62|elevator_fsm.sv:34|<techmap.v>:432" *)
  wire [15:0] _154_;
  (* src = "elevator_fsm.sv:62|elevator_fsm.sv:34|<techmap.v>:428" *)
  wire [3:0] _155_;
  wire _156_;
  wire _157_;
  wire _158_;
  wire _159_;
  (* src = "elevator_fsm.sv:82|elevator_fsm.sv:68|<techmap.v>:432" *)
  wire [15:0] _160_;
  (* src = "elevator_fsm.sv:82|elevator_fsm.sv:68|<techmap.v>:428" *)
  wire [7:0] _161_;
  wire _162_;
  (* src = "elevator_fsm.sv:87" *)
  (* unused_bits = "8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31" *)
  wire [31:0] _163_;
  (* src = "elevator_fsm.sv:89|elevator_fsm.sv:68|<techmap.v>:445" *)
  wire _164_;
  (* src = "elevator_fsm.sv:89|elevator_fsm.sv:68|<techmap.v>:445" *)
  wire _165_;
  (* src = "elevator_fsm.sv:89|elevator_fsm.sv:68|<techmap.v>:445" *)
  wire _166_;
  (* src = "elevator_fsm.sv:89|elevator_fsm.sv:68|<techmap.v>:445" *)
  wire _167_;
  (* src = "elevator_fsm.sv:62|elevator_fsm.sv:34|<techmap.v>:445" *)
  wire _168_;
  (* src = "elevator_fsm.sv:82|elevator_fsm.sv:68|<techmap.v>:445" *)
  wire _169_;
  (* src = "elevator_fsm.sv:87|<techmap.v>:258" *)
  (* unused_bits = "8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31" *)
  wire [31:0] _170_;
  (* src = "elevator_fsm.sv:87|<techmap.v>:260|<techmap.v>:203" *)
  (* unused_bits = "7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31" *)
  wire [31:0] _171_;
  (* src = "elevator_fsm.sv:87|<techmap.v>:260|<techmap.v>:203" *)
  (* unused_bits = "1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31" *)
  wire [31:0] _172_;
  (* unused_bits = "8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31" *)
  wire [31:0] _173_;
  (* src = "elevator_fsm.sv:87|<techmap.v>:260" *)
  (* unused_bits = "7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31" *)
  wire [31:0] _174_;
  (* src = "elevator_fsm.sv:87|<techmap.v>:258" *)
  (* unused_bits = "8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31" *)
  wire [31:0] _175_;
  (* src = "elevator_fsm.sv:87|<techmap.v>:260|<techmap.v>:212" *)
  wire _176_;
  (* src = "elevator_fsm.sv:87|<techmap.v>:260|<techmap.v>:221" *)
  wire _177_;
  (* src = "elevator_fsm.sv:87|<techmap.v>:260|<techmap.v>:221" *)
  wire _178_;
  (* src = "elevator_fsm.sv:87|<techmap.v>:260|<techmap.v>:221" *)
  wire _179_;
  (* src = "elevator_fsm.sv:87|<techmap.v>:260|<techmap.v>:221" *)
  wire _180_;
  (* src = "elevator_fsm.sv:87|<techmap.v>:260|<techmap.v>:222" *)
  wire _181_;
  (* src = "elevator_fsm.sv:87|<techmap.v>:260|<techmap.v>:222" *)
  wire _182_;
  (* src = "elevator_fsm.sv:87|<techmap.v>:260|<techmap.v>:229" *)
  wire _183_;
  (* src = "elevator_fsm.sv:87|<techmap.v>:260|<techmap.v>:229" *)
  wire _184_;
  (* src = "elevator_fsm.sv:87|<techmap.v>:260|<techmap.v>:229" *)
  wire _185_;
  (* src = "elevator_fsm.sv:87|<techmap.v>:260|<techmap.v>:229" *)
  wire _186_;
  (* src = "elevator_fsm.sv:87|<techmap.v>:260|<techmap.v>:221" *)
  wire _187_;
  (* src = "elevator_fsm.sv:87|<techmap.v>:260|<techmap.v>:221" *)
  wire _188_;
  (* src = "elevator_fsm.sv:7" *)
  input [1:0] car_floor_req;
  (* src = "elevator_fsm.sv:3" *)
  input clk;
  (* src = "elevator_fsm.sv:14" *)
  output cmd_car_down;
  reg cmd_car_down;
  (* src = "elevator_fsm.sv:13" *)
  output cmd_car_up;
  reg cmd_car_up;
  (* src = "elevator_fsm.sv:12" *)
  output cmd_door_close;
  reg cmd_door_close;
  (* src = "elevator_fsm.sv:11" *)
  output cmd_door_open;
  reg cmd_door_open;
  (* src = "elevator_fsm.sv:6" *)
  input door_close_req;
  (* src = "elevator_fsm.sv:22" *)
  reg [7:0] door_close_timer;
  (* src = "elevator_fsm.sv:5" *)
  input door_open_req;
  (* src = "elevator_fsm.sv:8" *)
  input floor_1_cab_req;
  (* src = "elevator_fsm.sv:9" *)
  input floor_2_cab_req;
  (* src = "elevator_fsm.sv:10" *)
  input [1:0] floor_sensor;
  (* src = "elevator_fsm.sv:23" *)
  wire [3:0] next_state;
  (* src = "elevator_fsm.sv:4" *)
  input rst;
  (* src = "elevator_fsm.sv:21" *)
  reg [3:0] state;
  assign _021_[0] = _064_[0] |(* src = "elevator_fsm.sv:55" *)  _064_[1];
  assign _021_[1] = _064_[2] |(* src = "elevator_fsm.sv:55" *)  _064_[3];
  assign _021_[2] = _064_[4] |(* src = "elevator_fsm.sv:55" *)  _064_[5];
  assign _021_[3] = _064_[6] |(* src = "elevator_fsm.sv:55" *)  _064_[7];
  assign _021_[4] = _064_[8] |(* src = "elevator_fsm.sv:55" *)  _064_[9];
  assign _021_[5] = _064_[10] |(* src = "elevator_fsm.sv:55" *)  _064_[11];
  assign _021_[6] = _064_[12] |(* src = "elevator_fsm.sv:55" *)  _064_[13];
  assign _021_[7] = _064_[14] |(* src = "elevator_fsm.sv:55" *)  _064_[15];
  assign _021_[8] = _064_[16] |(* src = "elevator_fsm.sv:55" *)  _064_[17];
  assign _021_[9] = _064_[18] |(* src = "elevator_fsm.sv:55" *)  _064_[19];
  assign _021_[10] = _064_[20] |(* src = "elevator_fsm.sv:55" *)  _064_[21];
  assign _021_[11] = _064_[22] |(* src = "elevator_fsm.sv:55" *)  _064_[23];
  assign _021_[12] = _064_[24] |(* src = "elevator_fsm.sv:55" *)  _064_[25];
  assign _021_[13] = _064_[26] |(* src = "elevator_fsm.sv:55" *)  _064_[27];
  assign _021_[14] = _064_[28] |(* src = "elevator_fsm.sv:55" *)  _064_[29];
  assign _021_[15] = _064_[30] |(* src = "elevator_fsm.sv:55" *)  _064_[31];
  assign _022_[0] = _021_[0] |(* src = "elevator_fsm.sv:55" *)  _021_[1];
  assign _022_[1] = _021_[2] |(* src = "elevator_fsm.sv:55" *)  _021_[3];
  assign _022_[2] = _021_[4] |(* src = "elevator_fsm.sv:55" *)  _021_[5];
  assign _022_[3] = _021_[6] |(* src = "elevator_fsm.sv:55" *)  _021_[7];
  assign _022_[4] = _021_[8] |(* src = "elevator_fsm.sv:55" *)  _021_[9];
  assign _022_[5] = _021_[10] |(* src = "elevator_fsm.sv:55" *)  _021_[11];
  assign _022_[6] = _021_[12] |(* src = "elevator_fsm.sv:55" *)  _021_[13];
  assign _022_[7] = _021_[14] |(* src = "elevator_fsm.sv:55" *)  _021_[15];
  assign _023_[0] = _022_[0] |(* src = "elevator_fsm.sv:55" *)  _022_[1];
  assign _023_[1] = _022_[2] |(* src = "elevator_fsm.sv:55" *)  _022_[3];
  assign _023_[2] = _022_[4] |(* src = "elevator_fsm.sv:55" *)  _022_[5];
  assign _023_[3] = _022_[6] |(* src = "elevator_fsm.sv:55" *)  _022_[7];
  assign _024_[0] = _023_[0] |(* src = "elevator_fsm.sv:55" *)  _023_[1];
  assign _024_[1] = _023_[2] |(* src = "elevator_fsm.sv:55" *)  _023_[3];
  assign _091_ = _024_[0] |(* src = "elevator_fsm.sv:55" *)  _024_[1];
  assign _025_[0] = _065_[0] |(* src = "elevator_fsm.sv:82|elevator_fsm.sv:68" *)  _065_[1];
  assign _025_[1] = _065_[2] |(* src = "elevator_fsm.sv:82|elevator_fsm.sv:68" *)  _065_[3];
  assign _092_ = _025_[0] |(* src = "elevator_fsm.sv:82|elevator_fsm.sv:68" *)  _025_[1];
  assign _026_[0] = _066_[0] |(* src = "elevator_fsm.sv:75|elevator_fsm.sv:68" *)  _066_[1];
  assign _026_[1] = _066_[2] |(* src = "elevator_fsm.sv:75|elevator_fsm.sv:68" *)  _066_[3];
  assign _093_ = _026_[0] |(* src = "elevator_fsm.sv:75|elevator_fsm.sv:68" *)  _026_[1];
  assign _027_[0] = _067_[0] |(* src = "elevator_fsm.sv:89|elevator_fsm.sv:68" *)  _067_[1];
  assign _027_[1] = _067_[2] |(* src = "elevator_fsm.sv:89|elevator_fsm.sv:68" *)  _067_[3];
  assign _094_ = _027_[0] |(* src = "elevator_fsm.sv:89|elevator_fsm.sv:68" *)  _027_[1];
  assign _028_[0] = _068_[0] |(* src = "elevator_fsm.sv:82|elevator_fsm.sv:68" *)  _068_[1];
  assign _028_[1] = _068_[2] |(* src = "elevator_fsm.sv:82|elevator_fsm.sv:68" *)  _068_[3];
  assign _095_ = _028_[0] |(* src = "elevator_fsm.sv:82|elevator_fsm.sv:68" *)  _028_[1];
  assign _029_[0] = _069_[0] |(* src = "elevator_fsm.sv:75|elevator_fsm.sv:68" *)  _069_[1];
  assign _029_[1] = _069_[2] |(* src = "elevator_fsm.sv:75|elevator_fsm.sv:68" *)  _069_[3];
  assign _096_ = _029_[0] |(* src = "elevator_fsm.sv:75|elevator_fsm.sv:68" *)  _029_[1];
  assign _030_[0] = _070_[0] |(* src = "elevator_fsm.sv:69|elevator_fsm.sv:68" *)  _070_[1];
  assign _030_[1] = _070_[2] |(* src = "elevator_fsm.sv:69|elevator_fsm.sv:68" *)  _070_[3];
  assign _097_ = _030_[0] |(* src = "elevator_fsm.sv:69|elevator_fsm.sv:68" *)  _030_[1];
  assign _031_[0] = _071_[0] |(* src = "elevator_fsm.sv:89|elevator_fsm.sv:68" *)  _071_[1];
  assign _031_[1] = _071_[2] |(* src = "elevator_fsm.sv:89|elevator_fsm.sv:68" *)  _071_[3];
  assign _098_ = _031_[0] |(* src = "elevator_fsm.sv:89|elevator_fsm.sv:68" *)  _031_[1];
  assign _032_[0] = _072_[0] |(* src = "elevator_fsm.sv:82|elevator_fsm.sv:68" *)  _072_[1];
  assign _032_[1] = _072_[2] |(* src = "elevator_fsm.sv:82|elevator_fsm.sv:68" *)  _072_[3];
  assign _099_ = _032_[0] |(* src = "elevator_fsm.sv:82|elevator_fsm.sv:68" *)  _032_[1];
  assign _033_[0] = _073_[0] |(* src = "elevator_fsm.sv:75|elevator_fsm.sv:68" *)  _073_[1];
  assign _033_[1] = _073_[2] |(* src = "elevator_fsm.sv:75|elevator_fsm.sv:68" *)  _073_[3];
  assign _100_ = _033_[0] |(* src = "elevator_fsm.sv:75|elevator_fsm.sv:68" *)  _033_[1];
  assign _034_[0] = _074_[0] |(* src = "elevator_fsm.sv:69|elevator_fsm.sv:68" *)  _074_[1];
  assign _034_[1] = _074_[2] |(* src = "elevator_fsm.sv:69|elevator_fsm.sv:68" *)  _074_[3];
  assign _101_ = _034_[0] |(* src = "elevator_fsm.sv:69|elevator_fsm.sv:68" *)  _034_[1];
  assign _035_[0] = _075_[0] |(* src = "elevator_fsm.sv:89|elevator_fsm.sv:68" *)  _075_[1];
  assign _035_[1] = _075_[2] |(* src = "elevator_fsm.sv:89|elevator_fsm.sv:68" *)  _075_[3];
  assign _102_ = _035_[0] |(* src = "elevator_fsm.sv:89|elevator_fsm.sv:68" *)  _035_[1];
  assign _036_[0] = _076_[0] |(* src = "elevator_fsm.sv:82|elevator_fsm.sv:68" *)  _076_[1];
  assign _036_[1] = _076_[2] |(* src = "elevator_fsm.sv:82|elevator_fsm.sv:68" *)  _076_[3];
  assign _103_ = _036_[0] |(* src = "elevator_fsm.sv:82|elevator_fsm.sv:68" *)  _036_[1];
  assign _037_[0] = _077_[0] |(* src = "elevator_fsm.sv:75|elevator_fsm.sv:68" *)  _077_[1];
  assign _037_[1] = _077_[2] |(* src = "elevator_fsm.sv:75|elevator_fsm.sv:68" *)  _077_[3];
  assign _104_ = _037_[0] |(* src = "elevator_fsm.sv:75|elevator_fsm.sv:68" *)  _037_[1];
  assign _038_[0] = _078_[0] |(* src = "elevator_fsm.sv:69|elevator_fsm.sv:68" *)  _078_[1];
  assign _038_[1] = _078_[2] |(* src = "elevator_fsm.sv:69|elevator_fsm.sv:68" *)  _078_[3];
  assign _105_ = _038_[0] |(* src = "elevator_fsm.sv:69|elevator_fsm.sv:68" *)  _038_[1];
  assign _039_[0] = _079_[0] |(* src = "elevator_fsm.sv:89|elevator_fsm.sv:68" *)  _079_[1];
  assign _039_[1] = _079_[2] |(* src = "elevator_fsm.sv:89|elevator_fsm.sv:68" *)  _079_[3];
  assign _106_ = _039_[0] |(* src = "elevator_fsm.sv:89|elevator_fsm.sv:68" *)  _039_[1];
  assign _040_[0] = _080_[0] |(* src = "elevator_fsm.sv:82|elevator_fsm.sv:68" *)  _080_[1];
  assign _040_[1] = _080_[2] |(* src = "elevator_fsm.sv:82|elevator_fsm.sv:68" *)  _080_[3];
  assign _107_ = _040_[0] |(* src = "elevator_fsm.sv:82|elevator_fsm.sv:68" *)  _040_[1];
  assign _041_[0] = _081_[0] |(* src = "elevator_fsm.sv:75|elevator_fsm.sv:68" *)  _081_[1];
  assign _041_[1] = _081_[2] |(* src = "elevator_fsm.sv:75|elevator_fsm.sv:68" *)  _081_[3];
  assign _108_ = _041_[0] |(* src = "elevator_fsm.sv:75|elevator_fsm.sv:68" *)  _041_[1];
  assign _042_[0] = _082_[0] |(* src = "elevator_fsm.sv:69|elevator_fsm.sv:68" *)  _082_[1];
  assign _042_[1] = _082_[2] |(* src = "elevator_fsm.sv:69|elevator_fsm.sv:68" *)  _082_[3];
  assign _109_ = _042_[0] |(* src = "elevator_fsm.sv:69|elevator_fsm.sv:68" *)  _042_[1];
  assign _043_[0] = _083_[0] |(* src = "elevator_fsm.sv:54|elevator_fsm.sv:34" *)  _083_[1];
  assign _043_[1] = _083_[2] |(* src = "elevator_fsm.sv:54|elevator_fsm.sv:34" *)  _083_[3];
  assign _110_ = _043_[0] |(* src = "elevator_fsm.sv:54|elevator_fsm.sv:34" *)  _043_[1];
  assign _044_[0] = _084_[0] |(* src = "elevator_fsm.sv:46|elevator_fsm.sv:34" *)  _084_[1];
  assign _044_[1] = _084_[2] |(* src = "elevator_fsm.sv:46|elevator_fsm.sv:34" *)  _084_[3];
  assign _111_ = _044_[0] |(* src = "elevator_fsm.sv:46|elevator_fsm.sv:34" *)  _044_[1];
  assign _045_[0] = _085_[0] |(* src = "elevator_fsm.sv:35|elevator_fsm.sv:34" *)  _085_[1];
  assign _045_[1] = _085_[2] |(* src = "elevator_fsm.sv:35|elevator_fsm.sv:34" *)  _085_[3];
  assign _112_ = _045_[0] |(* src = "elevator_fsm.sv:35|elevator_fsm.sv:34" *)  _045_[1];
  assign _046_[0] = _086_[0] |(* src = "elevator_fsm.sv:35|elevator_fsm.sv:34" *)  _086_[1];
  assign _046_[1] = _086_[2] |(* src = "elevator_fsm.sv:35|elevator_fsm.sv:34" *)  _086_[3];
  assign _113_ = _046_[0] |(* src = "elevator_fsm.sv:35|elevator_fsm.sv:34" *)  _046_[1];
  assign _047_[0] = _087_[0] |(* src = "elevator_fsm.sv:62|elevator_fsm.sv:34" *)  _087_[1];
  assign _047_[1] = _087_[2] |(* src = "elevator_fsm.sv:62|elevator_fsm.sv:34" *)  _087_[3];
  assign _114_ = _047_[0] |(* src = "elevator_fsm.sv:62|elevator_fsm.sv:34" *)  _047_[1];
  assign _048_[0] = _088_[0] |(* src = "elevator_fsm.sv:54|elevator_fsm.sv:34" *)  _088_[1];
  assign _048_[1] = _088_[2] |(* src = "elevator_fsm.sv:54|elevator_fsm.sv:34" *)  _088_[3];
  assign _115_ = _048_[0] |(* src = "elevator_fsm.sv:54|elevator_fsm.sv:34" *)  _048_[1];
  assign _049_[0] = _089_[0] |(* src = "elevator_fsm.sv:46|elevator_fsm.sv:34" *)  _089_[1];
  assign _049_[1] = _089_[2] |(* src = "elevator_fsm.sv:46|elevator_fsm.sv:34" *)  _089_[3];
  assign _116_ = _049_[0] |(* src = "elevator_fsm.sv:46|elevator_fsm.sv:34" *)  _049_[1];
  assign _050_[0] = _090_[0] |(* src = "elevator_fsm.sv:35|elevator_fsm.sv:34" *)  _090_[1];
  assign _050_[1] = _090_[2] |(* src = "elevator_fsm.sv:35|elevator_fsm.sv:34" *)  _090_[3];
  assign _117_ = _050_[0] |(* src = "elevator_fsm.sv:35|elevator_fsm.sv:34" *)  _050_[1];
  assign _161_[7] = _160_[7] |(* src = "elevator_fsm.sv:82|elevator_fsm.sv:68|<techmap.v>:441" *)  _160_[15];
  assign _161_[6] = _160_[6] |(* src = "elevator_fsm.sv:82|elevator_fsm.sv:68|<techmap.v>:441" *)  _160_[14];
  assign _161_[5] = _160_[5] |(* src = "elevator_fsm.sv:82|elevator_fsm.sv:68|<techmap.v>:441" *)  _160_[13];
  assign _161_[4] = _160_[4] |(* src = "elevator_fsm.sv:82|elevator_fsm.sv:68|<techmap.v>:441" *)  _160_[12];
  assign _161_[3] = _160_[3] |(* src = "elevator_fsm.sv:82|elevator_fsm.sv:68|<techmap.v>:441" *)  _160_[11];
  assign _161_[2] = _160_[2] |(* src = "elevator_fsm.sv:82|elevator_fsm.sv:68|<techmap.v>:441" *)  _160_[10];
  assign _161_[1] = _160_[1] |(* src = "elevator_fsm.sv:82|elevator_fsm.sv:68|<techmap.v>:441" *)  _160_[9];
  assign _161_[0] = _160_[0] |(* src = "elevator_fsm.sv:82|elevator_fsm.sv:68|<techmap.v>:441" *)  _160_[8];
  assign _169_ = _162_ |(* src = "elevator_fsm.sv:82|elevator_fsm.sv:68|<techmap.v>:445" *)  _120_;
  assign _051_[0] = _121_[0] |(* src = "elevator_fsm.sv:89|elevator_fsm.sv:68|<techmap.v>:441" *)  _121_[1];
  assign _051_[1] = _121_[2] |(* src = "elevator_fsm.sv:89|elevator_fsm.sv:68|<techmap.v>:441" *)  _121_[3];
  assign _122_ = _051_[0] |(* src = "elevator_fsm.sv:89|elevator_fsm.sv:68|<techmap.v>:441" *)  _051_[1];
  assign _052_[0] = _123_ |(* src = "elevator_fsm.sv:89|elevator_fsm.sv:68|<techmap.v>:445" *)  _124_;
  assign _052_[1] = _125_ |(* src = "elevator_fsm.sv:89|elevator_fsm.sv:68|<techmap.v>:445" *)  _126_;
  assign _164_ = _052_[0] |(* src = "elevator_fsm.sv:89|elevator_fsm.sv:68|<techmap.v>:445" *)  _052_[1];
  assign _053_[0] = _127_[0] |(* src = "elevator_fsm.sv:89|elevator_fsm.sv:68|<techmap.v>:441" *)  _127_[1];
  assign _053_[1] = _127_[2] |(* src = "elevator_fsm.sv:89|elevator_fsm.sv:68|<techmap.v>:441" *)  _127_[3];
  assign _128_ = _053_[0] |(* src = "elevator_fsm.sv:89|elevator_fsm.sv:68|<techmap.v>:441" *)  _053_[1];
  assign _054_[0] = _129_ |(* src = "elevator_fsm.sv:89|elevator_fsm.sv:68|<techmap.v>:445" *)  _130_;
  assign _054_[1] = _131_ |(* src = "elevator_fsm.sv:89|elevator_fsm.sv:68|<techmap.v>:445" *)  _132_;
  assign _165_ = _054_[0] |(* src = "elevator_fsm.sv:89|elevator_fsm.sv:68|<techmap.v>:445" *)  _054_[1];
  assign _055_[0] = _133_[0] |(* src = "elevator_fsm.sv:89|elevator_fsm.sv:68|<techmap.v>:441" *)  _133_[1];
  assign _055_[1] = _133_[2] |(* src = "elevator_fsm.sv:89|elevator_fsm.sv:68|<techmap.v>:441" *)  _133_[3];
  assign _134_ = _055_[0] |(* src = "elevator_fsm.sv:89|elevator_fsm.sv:68|<techmap.v>:441" *)  _055_[1];
  assign _056_[0] = _135_ |(* src = "elevator_fsm.sv:89|elevator_fsm.sv:68|<techmap.v>:445" *)  _136_;
  assign _056_[1] = _137_ |(* src = "elevator_fsm.sv:89|elevator_fsm.sv:68|<techmap.v>:445" *)  _138_;
  assign _166_ = _056_[0] |(* src = "elevator_fsm.sv:89|elevator_fsm.sv:68|<techmap.v>:445" *)  _056_[1];
  assign _057_[0] = _139_[0] |(* src = "elevator_fsm.sv:89|elevator_fsm.sv:68|<techmap.v>:441" *)  _139_[1];
  assign _057_[1] = _139_[2] |(* src = "elevator_fsm.sv:89|elevator_fsm.sv:68|<techmap.v>:441" *)  _139_[3];
  assign _140_ = _057_[0] |(* src = "elevator_fsm.sv:89|elevator_fsm.sv:68|<techmap.v>:441" *)  _057_[1];
  assign _058_[0] = _141_ |(* src = "elevator_fsm.sv:89|elevator_fsm.sv:68|<techmap.v>:445" *)  _142_;
  assign _058_[1] = _143_ |(* src = "elevator_fsm.sv:89|elevator_fsm.sv:68|<techmap.v>:445" *)  _144_;
  assign _167_ = _058_[0] |(* src = "elevator_fsm.sv:89|elevator_fsm.sv:68|<techmap.v>:445" *)  _058_[1];
  assign _059_[0] = _154_[3] |(* src = "elevator_fsm.sv:62|elevator_fsm.sv:34|<techmap.v>:441" *)  _154_[7];
  assign _059_[1] = _154_[11] |(* src = "elevator_fsm.sv:62|elevator_fsm.sv:34|<techmap.v>:441" *)  _154_[15];
  assign _155_[3] = _059_[0] |(* src = "elevator_fsm.sv:62|elevator_fsm.sv:34|<techmap.v>:441" *)  _059_[1];
  assign _060_[0] = _154_[2] |(* src = "elevator_fsm.sv:62|elevator_fsm.sv:34|<techmap.v>:441" *)  _154_[6];
  assign _060_[1] = _154_[10] |(* src = "elevator_fsm.sv:62|elevator_fsm.sv:34|<techmap.v>:441" *)  _154_[14];
  assign _155_[2] = _060_[0] |(* src = "elevator_fsm.sv:62|elevator_fsm.sv:34|<techmap.v>:441" *)  _060_[1];
  assign _061_[0] = _154_[1] |(* src = "elevator_fsm.sv:62|elevator_fsm.sv:34|<techmap.v>:441" *)  _154_[5];
  assign _061_[1] = _154_[9] |(* src = "elevator_fsm.sv:62|elevator_fsm.sv:34|<techmap.v>:441" *)  _154_[13];
  assign _155_[1] = _061_[0] |(* src = "elevator_fsm.sv:62|elevator_fsm.sv:34|<techmap.v>:441" *)  _061_[1];
  assign _062_[0] = _154_[0] |(* src = "elevator_fsm.sv:62|elevator_fsm.sv:34|<techmap.v>:441" *)  _154_[4];
  assign _062_[1] = _154_[8] |(* src = "elevator_fsm.sv:62|elevator_fsm.sv:34|<techmap.v>:441" *)  _154_[12];
  assign _155_[0] = _062_[0] |(* src = "elevator_fsm.sv:62|elevator_fsm.sv:34|<techmap.v>:441" *)  _062_[1];
  assign _063_[0] = _156_ |(* src = "elevator_fsm.sv:62|elevator_fsm.sv:34|<techmap.v>:445" *)  _157_;
  assign _063_[1] = _158_ |(* src = "elevator_fsm.sv:62|elevator_fsm.sv:34|<techmap.v>:445" *)  _159_;
  assign _168_ = _063_[0] |(* src = "elevator_fsm.sv:62|elevator_fsm.sv:34|<techmap.v>:445" *)  _063_[1];
  assign _118_ = ~(* src = "elevator_fsm.sv:55" *) _091_;
  assign _162_ = ~(* src = "elevator_fsm.sv:82|elevator_fsm.sv:68" *) _092_;
  assign _120_ = ~(* src = "elevator_fsm.sv:75|elevator_fsm.sv:68" *) _093_;
  assign _123_ = ~(* src = "elevator_fsm.sv:89|elevator_fsm.sv:68" *) _094_;
  assign _124_ = ~(* src = "elevator_fsm.sv:82|elevator_fsm.sv:68" *) _095_;
  assign _125_ = ~(* src = "elevator_fsm.sv:75|elevator_fsm.sv:68" *) _096_;
  assign _126_ = ~(* src = "elevator_fsm.sv:69|elevator_fsm.sv:68" *) _097_;
  assign _129_ = ~(* src = "elevator_fsm.sv:89|elevator_fsm.sv:68" *) _098_;
  assign _130_ = ~(* src = "elevator_fsm.sv:82|elevator_fsm.sv:68" *) _099_;
  assign _131_ = ~(* src = "elevator_fsm.sv:75|elevator_fsm.sv:68" *) _100_;
  assign _132_ = ~(* src = "elevator_fsm.sv:69|elevator_fsm.sv:68" *) _101_;
  assign _135_ = ~(* src = "elevator_fsm.sv:89|elevator_fsm.sv:68" *) _102_;
  assign _136_ = ~(* src = "elevator_fsm.sv:82|elevator_fsm.sv:68" *) _103_;
  assign _137_ = ~(* src = "elevator_fsm.sv:75|elevator_fsm.sv:68" *) _104_;
  assign _138_ = ~(* src = "elevator_fsm.sv:69|elevator_fsm.sv:68" *) _105_;
  assign _141_ = ~(* src = "elevator_fsm.sv:89|elevator_fsm.sv:68" *) _106_;
  assign _142_ = ~(* src = "elevator_fsm.sv:82|elevator_fsm.sv:68" *) _107_;
  assign _143_ = ~(* src = "elevator_fsm.sv:75|elevator_fsm.sv:68" *) _108_;
  assign _144_ = ~(* src = "elevator_fsm.sv:69|elevator_fsm.sv:68" *) _109_;
  assign _146_ = ~(* src = "elevator_fsm.sv:54|elevator_fsm.sv:34" *) _110_;
  assign _148_ = ~(* src = "elevator_fsm.sv:46|elevator_fsm.sv:34" *) _111_;
  assign _151_ = ~(* src = "elevator_fsm.sv:35|elevator_fsm.sv:34" *) _112_;
  assign _153_ = ~(* src = "elevator_fsm.sv:35|elevator_fsm.sv:34" *) _113_;
  assign _156_ = ~(* src = "elevator_fsm.sv:62|elevator_fsm.sv:34" *) _114_;
  assign _157_ = ~(* src = "elevator_fsm.sv:54|elevator_fsm.sv:34" *) _115_;
  assign _158_ = ~(* src = "elevator_fsm.sv:46|elevator_fsm.sv:34" *) _116_;
  assign _159_ = ~(* src = "elevator_fsm.sv:35|elevator_fsm.sv:34" *) _117_;
  assign _170_[0] = 1'h1 ? (* src = "elevator_fsm.sv:87|<techmap.v>:258" *) _175_[0] : 1'h1;
  assign _170_[1] = 1'h1 ? (* src = "elevator_fsm.sv:87|<techmap.v>:258" *) _175_[1] : 1'h0;
  assign _170_[2] = 1'h1 ? (* src = "elevator_fsm.sv:87|<techmap.v>:258" *) _175_[2] : 1'h0;
  assign _170_[3] = 1'h1 ? (* src = "elevator_fsm.sv:87|<techmap.v>:258" *) _175_[3] : 1'h0;
  assign _170_[4] = 1'h1 ? (* src = "elevator_fsm.sv:87|<techmap.v>:258" *) _175_[4] : 1'h0;
  assign _170_[5] = 1'h1 ? (* src = "elevator_fsm.sv:87|<techmap.v>:258" *) _175_[5] : 1'h0;
  assign _170_[6] = 1'h1 ? (* src = "elevator_fsm.sv:87|<techmap.v>:258" *) _175_[6] : 1'h0;
  assign _170_[7] = 1'h1 ? (* src = "elevator_fsm.sv:87|<techmap.v>:258" *) _175_[7] : 1'h0;
  assign _145_[0] = _118_ ? (* src = "elevator_fsm.sv:55" *) 1'h0 : 1'h0;
  assign _145_[1] = _118_ ? (* src = "elevator_fsm.sv:55" *) 1'h0 : 1'h0;
  assign _145_[2] = _118_ ? (* src = "elevator_fsm.sv:55" *) 1'h0 : 1'h1;
  assign _145_[3] = _118_ ? (* src = "elevator_fsm.sv:55" *) 1'h1 : 1'h0;
  assign _011_[0] = _146_ ? (* src = "elevator_fsm.sv:54|elevator_fsm.sv:34" *) _145_[0] : _145_[0];
  assign _011_[1] = _146_ ? (* src = "elevator_fsm.sv:54|elevator_fsm.sv:34" *) _145_[1] : _145_[1];
  assign _011_[2] = _146_ ? (* src = "elevator_fsm.sv:54|elevator_fsm.sv:34" *) _145_[2] : _145_[2];
  assign _011_[3] = _146_ ? (* src = "elevator_fsm.sv:54|elevator_fsm.sv:34" *) _145_[3] : _145_[3];
  assign _147_[0] = door_open_req ? (* src = "elevator_fsm.sv:47" *) 1'h0 : 1'h0;
  assign _147_[1] = door_open_req ? (* src = "elevator_fsm.sv:47" *) 1'h1 : 1'h0;
  assign _147_[2] = door_open_req ? (* src = "elevator_fsm.sv:47" *) 1'h0 : 1'h1;
  assign _147_[3] = door_open_req ? (* src = "elevator_fsm.sv:47" *) 1'h0 : 1'h0;
  assign _010_[0] = _148_ ? (* src = "elevator_fsm.sv:46|elevator_fsm.sv:34" *) _147_[0] : _147_[0];
  assign _010_[1] = _148_ ? (* src = "elevator_fsm.sv:46|elevator_fsm.sv:34" *) _147_[1] : _147_[1];
  assign _010_[2] = _148_ ? (* src = "elevator_fsm.sv:46|elevator_fsm.sv:34" *) _147_[2] : _147_[2];
  assign _010_[3] = _148_ ? (* src = "elevator_fsm.sv:46|elevator_fsm.sv:34" *) _147_[3] : _147_[3];
  assign _149_[0] = door_close_req ? (* src = "elevator_fsm.sv:39" *) 1'h0 : 1'h1;
  assign _149_[1] = door_close_req ? (* src = "elevator_fsm.sv:39" *) 1'h0 : 1'h0;
  assign _149_[2] = door_close_req ? (* src = "elevator_fsm.sv:39" *) 1'h0 : 1'h0;
  assign _149_[3] = door_close_req ? (* src = "elevator_fsm.sv:39" *) 1'h1 : 1'h0;
  assign _150_[0] = 1'h0 ? (* src = "elevator_fsm.sv:36" *) _149_[0] : _149_[0];
  assign _150_[1] = 1'h0 ? (* src = "elevator_fsm.sv:36" *) _149_[1] : _149_[1];
  assign _150_[2] = 1'h0 ? (* src = "elevator_fsm.sv:36" *) _149_[2] : _149_[2];
  assign _150_[3] = 1'h0 ? (* src = "elevator_fsm.sv:36" *) _149_[3] : _149_[3];
  assign _009_[0] = _151_ ? (* src = "elevator_fsm.sv:35|elevator_fsm.sv:34" *) _150_[0] : _150_[0];
  assign _009_[1] = _151_ ? (* src = "elevator_fsm.sv:35|elevator_fsm.sv:34" *) _150_[1] : _150_[1];
  assign _009_[2] = _151_ ? (* src = "elevator_fsm.sv:35|elevator_fsm.sv:34" *) _150_[2] : _150_[2];
  assign _009_[3] = _151_ ? (* src = "elevator_fsm.sv:35|elevator_fsm.sv:34" *) _150_[3] : _150_[3];
  assign _152_[0] = door_open_req ? (* src = "elevator_fsm.sv:36" *) 1'h0 : _009_[0];
  assign _152_[1] = door_open_req ? (* src = "elevator_fsm.sv:36" *) 1'h1 : _009_[1];
  assign _152_[2] = door_open_req ? (* src = "elevator_fsm.sv:36" *) 1'h0 : _009_[2];
  assign _152_[3] = door_open_req ? (* src = "elevator_fsm.sv:36" *) 1'h0 : _009_[3];
  assign _008_[0] = _153_ ? (* src = "elevator_fsm.sv:35|elevator_fsm.sv:34" *) _152_[0] : _152_[0];
  assign _008_[1] = _153_ ? (* src = "elevator_fsm.sv:35|elevator_fsm.sv:34" *) _152_[1] : _152_[1];
  assign _008_[2] = _153_ ? (* src = "elevator_fsm.sv:35|elevator_fsm.sv:34" *) _152_[2] : _152_[2];
  assign _008_[3] = _153_ ? (* src = "elevator_fsm.sv:35|elevator_fsm.sv:34" *) _152_[3] : _152_[3];
  assign _004_[0] = _119_ ? (* src = "elevator_fsm.sv:25" *) 1'h0 : door_close_timer[0];
  assign _004_[1] = _119_ ? (* src = "elevator_fsm.sv:25" *) 1'h0 : door_close_timer[1];
  assign _004_[2] = _119_ ? (* src = "elevator_fsm.sv:25" *) 1'h0 : door_close_timer[2];
  assign _004_[3] = _119_ ? (* src = "elevator_fsm.sv:25" *) 1'h0 : door_close_timer[3];
  assign _004_[4] = _119_ ? (* src = "elevator_fsm.sv:25" *) 1'h0 : door_close_timer[4];
  assign _004_[5] = _119_ ? (* src = "elevator_fsm.sv:25" *) 1'h0 : door_close_timer[5];
  assign _004_[6] = _119_ ? (* src = "elevator_fsm.sv:25" *) 1'h0 : door_close_timer[6];
  assign _004_[7] = _119_ ? (* src = "elevator_fsm.sv:25" *) 1'h0 : door_close_timer[7];
  assign _006_[0] = _119_ ? (* src = "elevator_fsm.sv:25" *) 1'h1 : next_state[0];
  assign _006_[1] = _119_ ? (* src = "elevator_fsm.sv:25" *) 1'h0 : next_state[1];
  assign _006_[2] = _119_ ? (* src = "elevator_fsm.sv:25" *) 1'h0 : next_state[2];
  assign _006_[3] = _119_ ? (* src = "elevator_fsm.sv:25" *) 1'h0 : next_state[3];
  assign _007_[0] = _169_ ? (* src = "elevator_fsm.sv:82|elevator_fsm.sv:68|<techmap.v>:445" *) _161_[0] : door_close_timer[0];
  assign _007_[1] = _169_ ? (* src = "elevator_fsm.sv:82|elevator_fsm.sv:68|<techmap.v>:445" *) _161_[1] : door_close_timer[1];
  assign _007_[2] = _169_ ? (* src = "elevator_fsm.sv:82|elevator_fsm.sv:68|<techmap.v>:445" *) _161_[2] : door_close_timer[2];
  assign _007_[3] = _169_ ? (* src = "elevator_fsm.sv:82|elevator_fsm.sv:68|<techmap.v>:445" *) _161_[3] : door_close_timer[3];
  assign _007_[4] = _169_ ? (* src = "elevator_fsm.sv:82|elevator_fsm.sv:68|<techmap.v>:445" *) _161_[4] : door_close_timer[4];
  assign _007_[5] = _169_ ? (* src = "elevator_fsm.sv:82|elevator_fsm.sv:68|<techmap.v>:445" *) _161_[5] : door_close_timer[5];
  assign _007_[6] = _169_ ? (* src = "elevator_fsm.sv:82|elevator_fsm.sv:68|<techmap.v>:445" *) _161_[6] : door_close_timer[6];
  assign _007_[7] = _169_ ? (* src = "elevator_fsm.sv:82|elevator_fsm.sv:68|<techmap.v>:445" *) _161_[7] : door_close_timer[7];
  assign _000_ = _164_ ? (* src = "elevator_fsm.sv:89|elevator_fsm.sv:68|<techmap.v>:445" *) _122_ : cmd_car_down;
  assign _001_ = _165_ ? (* src = "elevator_fsm.sv:89|elevator_fsm.sv:68|<techmap.v>:445" *) _128_ : cmd_car_up;
  assign _002_ = _166_ ? (* src = "elevator_fsm.sv:89|elevator_fsm.sv:68|<techmap.v>:445" *) _134_ : cmd_door_close;
  assign _003_ = _167_ ? (* src = "elevator_fsm.sv:89|elevator_fsm.sv:68|<techmap.v>:445" *) _140_ : cmd_door_open;
  assign _005_[0] = _168_ ? (* src = "elevator_fsm.sv:62|elevator_fsm.sv:34|<techmap.v>:445" *) _155_[0] : _008_[0];
  assign _005_[1] = _168_ ? (* src = "elevator_fsm.sv:62|elevator_fsm.sv:34|<techmap.v>:445" *) _155_[1] : _008_[1];
  assign _005_[2] = _168_ ? (* src = "elevator_fsm.sv:62|elevator_fsm.sv:34|<techmap.v>:445" *) _155_[2] : _008_[2];
  assign _005_[3] = _168_ ? (* src = "elevator_fsm.sv:62|elevator_fsm.sv:34|<techmap.v>:445" *) _155_[3] : _008_[3];
  assign _175_[0] = ~(* src = "elevator_fsm.sv:87|<techmap.v>:258" *) 1'h1;
  assign _175_[1] = ~(* src = "elevator_fsm.sv:87|<techmap.v>:258" *) 1'h0;
  assign _175_[2] = ~(* src = "elevator_fsm.sv:87|<techmap.v>:258" *) 1'h0;
  assign _175_[3] = ~(* src = "elevator_fsm.sv:87|<techmap.v>:258" *) 1'h0;
  assign _175_[4] = ~(* src = "elevator_fsm.sv:87|<techmap.v>:258" *) 1'h0;
  assign _175_[5] = ~(* src = "elevator_fsm.sv:87|<techmap.v>:258" *) 1'h0;
  assign _175_[6] = ~(* src = "elevator_fsm.sv:87|<techmap.v>:258" *) 1'h0;
  assign _175_[7] = ~(* src = "elevator_fsm.sv:87|<techmap.v>:258" *) 1'h0;
  assign _119_ = ~(* src = "elevator_fsm.sv:25" *) rst;
  assign _012_ = ~_018_;
  assign _013_ = ~(* src = "elevator_fsm.sv:33" *) _159_;
  assign _014_ = ~(* src = "elevator_fsm.sv:33" *) _158_;
  assign _015_ = ~(* src = "elevator_fsm.sv:33" *) _157_;
  assign _016_ = ~(* src = "elevator_fsm.sv:33" *) _156_;
  (* src = "elevator_fsm.sv:67" *)
  always @(posedge clk)
      cmd_door_open <= _003_;
  (* src = "elevator_fsm.sv:67" *)
  always @(posedge clk)
      cmd_door_close <= _002_;
  (* src = "elevator_fsm.sv:67" *)
  always @(posedge clk)
      cmd_car_up <= _001_;
  (* src = "elevator_fsm.sv:67" *)
  always @(posedge clk)
      cmd_car_down <= _000_;
  (* src = "elevator_fsm.sv:67" *)
  always @(posedge clk)
      door_close_timer[0] <= _007_[0];
  (* src = "elevator_fsm.sv:67" *)
  always @(posedge clk)
      door_close_timer[1] <= _007_[1];
  (* src = "elevator_fsm.sv:67" *)
  always @(posedge clk)
      door_close_timer[2] <= _007_[2];
  (* src = "elevator_fsm.sv:67" *)
  always @(posedge clk)
      door_close_timer[3] <= _007_[3];
  (* src = "elevator_fsm.sv:67" *)
  always @(posedge clk)
      door_close_timer[4] <= _007_[4];
  (* src = "elevator_fsm.sv:67" *)
  always @(posedge clk)
      door_close_timer[5] <= _007_[5];
  (* src = "elevator_fsm.sv:67" *)
  always @(posedge clk)
      door_close_timer[6] <= _007_[6];
  (* src = "elevator_fsm.sv:67" *)
  always @(posedge clk)
      door_close_timer[7] <= _007_[7];
  (* src = "elevator_fsm.sv:24" *)
  always @(posedge clk)
      state[0] <= _006_[0];
  (* src = "elevator_fsm.sv:24" *)
  always @(posedge clk)
      state[1] <= _006_[1];
  (* src = "elevator_fsm.sv:24" *)
  always @(posedge clk)
      state[2] <= _006_[2];
  (* src = "elevator_fsm.sv:24" *)
  always @(posedge clk)
      state[3] <= _006_[3];
  (* src = "elevator_fsm.sv:24" *)
  always @(posedge clk)
      door_close_timer[0] <= _004_[0];
  (* src = "elevator_fsm.sv:24" *)
  always @(posedge clk)
      door_close_timer[1] <= _004_[1];
  (* src = "elevator_fsm.sv:24" *)
  always @(posedge clk)
      door_close_timer[2] <= _004_[2];
  (* src = "elevator_fsm.sv:24" *)
  always @(posedge clk)
      door_close_timer[3] <= _004_[3];
  (* src = "elevator_fsm.sv:24" *)
  always @(posedge clk)
      door_close_timer[4] <= _004_[4];
  (* src = "elevator_fsm.sv:24" *)
  always @(posedge clk)
      door_close_timer[5] <= _004_[5];
  (* src = "elevator_fsm.sv:24" *)
  always @(posedge clk)
      door_close_timer[6] <= _004_[6];
  (* src = "elevator_fsm.sv:24" *)
  always @(posedge clk)
      door_close_timer[7] <= _004_[7];
  (* src = "elevator_fsm.sv:33" *)
  \$_DLATCH_P_  _483_ (
    .D(_005_[0]),
    .E(_012_),
    .Q(next_state[0])
  );
  (* src = "elevator_fsm.sv:33" *)
  \$_DLATCH_P_  _484_ (
    .D(_005_[1]),
    .E(_012_),
    .Q(next_state[1])
  );
  (* src = "elevator_fsm.sv:33" *)
  \$_DLATCH_P_  _485_ (
    .D(_005_[2]),
    .E(_012_),
    .Q(next_state[2])
  );
  (* src = "elevator_fsm.sv:33" *)
  \$_DLATCH_P_  _486_ (
    .D(_005_[3]),
    .E(_012_),
    .Q(next_state[3])
  );
  assign _176_ = _172_[0] &(* src = "elevator_fsm.sv:87|<techmap.v>:260|<techmap.v>:212" *)  1'h1;
  assign _177_ = _173_[1] &(* src = "elevator_fsm.sv:87|<techmap.v>:260|<techmap.v>:221" *)  _171_[0];
  assign _178_ = _173_[3] &(* src = "elevator_fsm.sv:87|<techmap.v>:260|<techmap.v>:221" *)  _174_[2];
  assign _179_ = _173_[5] &(* src = "elevator_fsm.sv:87|<techmap.v>:260|<techmap.v>:221" *)  _174_[4];
  assign _180_ = _181_ &(* src = "elevator_fsm.sv:87|<techmap.v>:260|<techmap.v>:221" *)  _171_[1];
  assign _181_ = _173_[3] &(* src = "elevator_fsm.sv:87|<techmap.v>:260|<techmap.v>:222" *)  _173_[2];
  assign _182_ = _173_[5] &(* src = "elevator_fsm.sv:87|<techmap.v>:260|<techmap.v>:222" *)  _173_[4];
  assign _183_ = _182_ &(* src = "elevator_fsm.sv:87|<techmap.v>:260|<techmap.v>:229" *)  _171_[3];
  assign _184_ = _173_[2] &(* src = "elevator_fsm.sv:87|<techmap.v>:260|<techmap.v>:229" *)  _171_[1];
  assign _185_ = _173_[4] &(* src = "elevator_fsm.sv:87|<techmap.v>:260|<techmap.v>:229" *)  _171_[3];
  assign _186_ = _173_[6] &(* src = "elevator_fsm.sv:87|<techmap.v>:260|<techmap.v>:229" *)  _171_[5];
  assign _171_[0] = _174_[0] |(* src = "elevator_fsm.sv:87|<techmap.v>:260|<techmap.v>:212" *)  _176_;
  assign _171_[1] = _174_[1] |(* src = "elevator_fsm.sv:87|<techmap.v>:260|<techmap.v>:221" *)  _177_;
  assign _187_ = _174_[3] |(* src = "elevator_fsm.sv:87|<techmap.v>:260|<techmap.v>:221" *)  _178_;
  assign _188_ = _174_[5] |(* src = "elevator_fsm.sv:87|<techmap.v>:260|<techmap.v>:221" *)  _179_;
  assign _171_[3] = _187_ |(* src = "elevator_fsm.sv:87|<techmap.v>:260|<techmap.v>:221" *)  _180_;
  assign _171_[5] = _188_ |(* src = "elevator_fsm.sv:87|<techmap.v>:260|<techmap.v>:229" *)  _183_;
  assign _171_[2] = _174_[2] |(* src = "elevator_fsm.sv:87|<techmap.v>:260|<techmap.v>:229" *)  _184_;
  assign _171_[4] = _174_[4] |(* src = "elevator_fsm.sv:87|<techmap.v>:260|<techmap.v>:229" *)  _185_;
  assign _171_[6] = _174_[6] |(* src = "elevator_fsm.sv:87|<techmap.v>:260|<techmap.v>:229" *)  _186_;
  assign _064_[0] = door_close_timer[0] ^(* src = "elevator_fsm.sv:55" *)  1'h0;
  assign _064_[1] = door_close_timer[1] ^(* src = "elevator_fsm.sv:55" *)  1'h0;
  assign _064_[2] = door_close_timer[2] ^(* src = "elevator_fsm.sv:55" *)  1'h0;
  assign _064_[3] = door_close_timer[3] ^(* src = "elevator_fsm.sv:55" *)  1'h0;
  assign _064_[4] = door_close_timer[4] ^(* src = "elevator_fsm.sv:55" *)  1'h0;
  assign _064_[5] = door_close_timer[5] ^(* src = "elevator_fsm.sv:55" *)  1'h0;
  assign _064_[6] = door_close_timer[6] ^(* src = "elevator_fsm.sv:55" *)  1'h0;
  assign _064_[7] = door_close_timer[7] ^(* src = "elevator_fsm.sv:55" *)  1'h0;
  assign _064_[8] = 1'h0 ^(* src = "elevator_fsm.sv:55" *)  1'h0;
  assign _064_[9] = 1'h0 ^(* src = "elevator_fsm.sv:55" *)  1'h0;
  assign _064_[10] = 1'h0 ^(* src = "elevator_fsm.sv:55" *)  1'h0;
  assign _064_[11] = 1'h0 ^(* src = "elevator_fsm.sv:55" *)  1'h0;
  assign _064_[12] = 1'h0 ^(* src = "elevator_fsm.sv:55" *)  1'h0;
  assign _064_[13] = 1'h0 ^(* src = "elevator_fsm.sv:55" *)  1'h0;
  assign _064_[14] = 1'h0 ^(* src = "elevator_fsm.sv:55" *)  1'h0;
  assign _064_[15] = 1'h0 ^(* src = "elevator_fsm.sv:55" *)  1'h0;
  assign _064_[16] = 1'h0 ^(* src = "elevator_fsm.sv:55" *)  1'h0;
  assign _064_[17] = 1'h0 ^(* src = "elevator_fsm.sv:55" *)  1'h0;
  assign _064_[18] = 1'h0 ^(* src = "elevator_fsm.sv:55" *)  1'h0;
  assign _064_[19] = 1'h0 ^(* src = "elevator_fsm.sv:55" *)  1'h0;
  assign _064_[20] = 1'h0 ^(* src = "elevator_fsm.sv:55" *)  1'h0;
  assign _064_[21] = 1'h0 ^(* src = "elevator_fsm.sv:55" *)  1'h0;
  assign _064_[22] = 1'h0 ^(* src = "elevator_fsm.sv:55" *)  1'h0;
  assign _064_[23] = 1'h0 ^(* src = "elevator_fsm.sv:55" *)  1'h0;
  assign _064_[24] = 1'h0 ^(* src = "elevator_fsm.sv:55" *)  1'h0;
  assign _064_[25] = 1'h0 ^(* src = "elevator_fsm.sv:55" *)  1'h0;
  assign _064_[26] = 1'h0 ^(* src = "elevator_fsm.sv:55" *)  1'h0;
  assign _064_[27] = 1'h0 ^(* src = "elevator_fsm.sv:55" *)  1'h0;
  assign _064_[28] = 1'h0 ^(* src = "elevator_fsm.sv:55" *)  1'h0;
  assign _064_[29] = 1'h0 ^(* src = "elevator_fsm.sv:55" *)  1'h0;
  assign _064_[30] = 1'h0 ^(* src = "elevator_fsm.sv:55" *)  1'h0;
  assign _064_[31] = 1'h0 ^(* src = "elevator_fsm.sv:55" *)  1'h0;
  assign _065_[0] = next_state[0] ^(* src = "elevator_fsm.sv:82|elevator_fsm.sv:68" *)  1'h0;
  assign _065_[1] = next_state[1] ^(* src = "elevator_fsm.sv:82|elevator_fsm.sv:68" *)  1'h0;
  assign _065_[2] = next_state[2] ^(* src = "elevator_fsm.sv:82|elevator_fsm.sv:68" *)  1'h1;
  assign _065_[3] = next_state[3] ^(* src = "elevator_fsm.sv:82|elevator_fsm.sv:68" *)  1'h0;
  assign _066_[0] = next_state[0] ^(* src = "elevator_fsm.sv:75|elevator_fsm.sv:68" *)  1'h0;
  assign _066_[1] = next_state[1] ^(* src = "elevator_fsm.sv:75|elevator_fsm.sv:68" *)  1'h1;
  assign _066_[2] = next_state[2] ^(* src = "elevator_fsm.sv:75|elevator_fsm.sv:68" *)  1'h0;
  assign _066_[3] = next_state[3] ^(* src = "elevator_fsm.sv:75|elevator_fsm.sv:68" *)  1'h0;
  assign _067_[0] = next_state[0] ^(* src = "elevator_fsm.sv:89|elevator_fsm.sv:68" *)  1'h0;
  assign _067_[1] = next_state[1] ^(* src = "elevator_fsm.sv:89|elevator_fsm.sv:68" *)  1'h0;
  assign _067_[2] = next_state[2] ^(* src = "elevator_fsm.sv:89|elevator_fsm.sv:68" *)  1'h0;
  assign _067_[3] = next_state[3] ^(* src = "elevator_fsm.sv:89|elevator_fsm.sv:68" *)  1'h1;
  assign _068_[0] = next_state[0] ^(* src = "elevator_fsm.sv:82|elevator_fsm.sv:68" *)  1'h0;
  assign _068_[1] = next_state[1] ^(* src = "elevator_fsm.sv:82|elevator_fsm.sv:68" *)  1'h0;
  assign _068_[2] = next_state[2] ^(* src = "elevator_fsm.sv:82|elevator_fsm.sv:68" *)  1'h1;
  assign _068_[3] = next_state[3] ^(* src = "elevator_fsm.sv:82|elevator_fsm.sv:68" *)  1'h0;
  assign _069_[0] = next_state[0] ^(* src = "elevator_fsm.sv:75|elevator_fsm.sv:68" *)  1'h0;
  assign _069_[1] = next_state[1] ^(* src = "elevator_fsm.sv:75|elevator_fsm.sv:68" *)  1'h1;
  assign _069_[2] = next_state[2] ^(* src = "elevator_fsm.sv:75|elevator_fsm.sv:68" *)  1'h0;
  assign _069_[3] = next_state[3] ^(* src = "elevator_fsm.sv:75|elevator_fsm.sv:68" *)  1'h0;
  assign _070_[0] = next_state[0] ^(* src = "elevator_fsm.sv:69|elevator_fsm.sv:68" *)  1'h1;
  assign _070_[1] = next_state[1] ^(* src = "elevator_fsm.sv:69|elevator_fsm.sv:68" *)  1'h0;
  assign _070_[2] = next_state[2] ^(* src = "elevator_fsm.sv:69|elevator_fsm.sv:68" *)  1'h0;
  assign _070_[3] = next_state[3] ^(* src = "elevator_fsm.sv:69|elevator_fsm.sv:68" *)  1'h0;
  assign _071_[0] = next_state[0] ^(* src = "elevator_fsm.sv:89|elevator_fsm.sv:68" *)  1'h0;
  assign _071_[1] = next_state[1] ^(* src = "elevator_fsm.sv:89|elevator_fsm.sv:68" *)  1'h0;
  assign _071_[2] = next_state[2] ^(* src = "elevator_fsm.sv:89|elevator_fsm.sv:68" *)  1'h0;
  assign _071_[3] = next_state[3] ^(* src = "elevator_fsm.sv:89|elevator_fsm.sv:68" *)  1'h1;
  assign _072_[0] = next_state[0] ^(* src = "elevator_fsm.sv:82|elevator_fsm.sv:68" *)  1'h0;
  assign _072_[1] = next_state[1] ^(* src = "elevator_fsm.sv:82|elevator_fsm.sv:68" *)  1'h0;
  assign _072_[2] = next_state[2] ^(* src = "elevator_fsm.sv:82|elevator_fsm.sv:68" *)  1'h1;
  assign _072_[3] = next_state[3] ^(* src = "elevator_fsm.sv:82|elevator_fsm.sv:68" *)  1'h0;
  assign _073_[0] = next_state[0] ^(* src = "elevator_fsm.sv:75|elevator_fsm.sv:68" *)  1'h0;
  assign _073_[1] = next_state[1] ^(* src = "elevator_fsm.sv:75|elevator_fsm.sv:68" *)  1'h1;
  assign _073_[2] = next_state[2] ^(* src = "elevator_fsm.sv:75|elevator_fsm.sv:68" *)  1'h0;
  assign _073_[3] = next_state[3] ^(* src = "elevator_fsm.sv:75|elevator_fsm.sv:68" *)  1'h0;
  assign _074_[0] = next_state[0] ^(* src = "elevator_fsm.sv:69|elevator_fsm.sv:68" *)  1'h1;
  assign _074_[1] = next_state[1] ^(* src = "elevator_fsm.sv:69|elevator_fsm.sv:68" *)  1'h0;
  assign _074_[2] = next_state[2] ^(* src = "elevator_fsm.sv:69|elevator_fsm.sv:68" *)  1'h0;
  assign _074_[3] = next_state[3] ^(* src = "elevator_fsm.sv:69|elevator_fsm.sv:68" *)  1'h0;
  assign _075_[0] = next_state[0] ^(* src = "elevator_fsm.sv:89|elevator_fsm.sv:68" *)  1'h0;
  assign _075_[1] = next_state[1] ^(* src = "elevator_fsm.sv:89|elevator_fsm.sv:68" *)  1'h0;
  assign _075_[2] = next_state[2] ^(* src = "elevator_fsm.sv:89|elevator_fsm.sv:68" *)  1'h0;
  assign _075_[3] = next_state[3] ^(* src = "elevator_fsm.sv:89|elevator_fsm.sv:68" *)  1'h1;
  assign _076_[0] = next_state[0] ^(* src = "elevator_fsm.sv:82|elevator_fsm.sv:68" *)  1'h0;
  assign _076_[1] = next_state[1] ^(* src = "elevator_fsm.sv:82|elevator_fsm.sv:68" *)  1'h0;
  assign _076_[2] = next_state[2] ^(* src = "elevator_fsm.sv:82|elevator_fsm.sv:68" *)  1'h1;
  assign _076_[3] = next_state[3] ^(* src = "elevator_fsm.sv:82|elevator_fsm.sv:68" *)  1'h0;
  assign _077_[0] = next_state[0] ^(* src = "elevator_fsm.sv:75|elevator_fsm.sv:68" *)  1'h0;
  assign _077_[1] = next_state[1] ^(* src = "elevator_fsm.sv:75|elevator_fsm.sv:68" *)  1'h1;
  assign _077_[2] = next_state[2] ^(* src = "elevator_fsm.sv:75|elevator_fsm.sv:68" *)  1'h0;
  assign _077_[3] = next_state[3] ^(* src = "elevator_fsm.sv:75|elevator_fsm.sv:68" *)  1'h0;
  assign _078_[0] = next_state[0] ^(* src = "elevator_fsm.sv:69|elevator_fsm.sv:68" *)  1'h1;
  assign _078_[1] = next_state[1] ^(* src = "elevator_fsm.sv:69|elevator_fsm.sv:68" *)  1'h0;
  assign _078_[2] = next_state[2] ^(* src = "elevator_fsm.sv:69|elevator_fsm.sv:68" *)  1'h0;
  assign _078_[3] = next_state[3] ^(* src = "elevator_fsm.sv:69|elevator_fsm.sv:68" *)  1'h0;
  assign _079_[0] = next_state[0] ^(* src = "elevator_fsm.sv:89|elevator_fsm.sv:68" *)  1'h0;
  assign _079_[1] = next_state[1] ^(* src = "elevator_fsm.sv:89|elevator_fsm.sv:68" *)  1'h0;
  assign _079_[2] = next_state[2] ^(* src = "elevator_fsm.sv:89|elevator_fsm.sv:68" *)  1'h0;
  assign _079_[3] = next_state[3] ^(* src = "elevator_fsm.sv:89|elevator_fsm.sv:68" *)  1'h1;
  assign _080_[0] = next_state[0] ^(* src = "elevator_fsm.sv:82|elevator_fsm.sv:68" *)  1'h0;
  assign _080_[1] = next_state[1] ^(* src = "elevator_fsm.sv:82|elevator_fsm.sv:68" *)  1'h0;
  assign _080_[2] = next_state[2] ^(* src = "elevator_fsm.sv:82|elevator_fsm.sv:68" *)  1'h1;
  assign _080_[3] = next_state[3] ^(* src = "elevator_fsm.sv:82|elevator_fsm.sv:68" *)  1'h0;
  assign _081_[0] = next_state[0] ^(* src = "elevator_fsm.sv:75|elevator_fsm.sv:68" *)  1'h0;
  assign _081_[1] = next_state[1] ^(* src = "elevator_fsm.sv:75|elevator_fsm.sv:68" *)  1'h1;
  assign _081_[2] = next_state[2] ^(* src = "elevator_fsm.sv:75|elevator_fsm.sv:68" *)  1'h0;
  assign _081_[3] = next_state[3] ^(* src = "elevator_fsm.sv:75|elevator_fsm.sv:68" *)  1'h0;
  assign _082_[0] = next_state[0] ^(* src = "elevator_fsm.sv:69|elevator_fsm.sv:68" *)  1'h1;
  assign _082_[1] = next_state[1] ^(* src = "elevator_fsm.sv:69|elevator_fsm.sv:68" *)  1'h0;
  assign _082_[2] = next_state[2] ^(* src = "elevator_fsm.sv:69|elevator_fsm.sv:68" *)  1'h0;
  assign _082_[3] = next_state[3] ^(* src = "elevator_fsm.sv:69|elevator_fsm.sv:68" *)  1'h0;
  assign _083_[0] = state[0] ^(* src = "elevator_fsm.sv:54|elevator_fsm.sv:34" *)  1'h0;
  assign _083_[1] = state[1] ^(* src = "elevator_fsm.sv:54|elevator_fsm.sv:34" *)  1'h0;
  assign _083_[2] = state[2] ^(* src = "elevator_fsm.sv:54|elevator_fsm.sv:34" *)  1'h1;
  assign _083_[3] = state[3] ^(* src = "elevator_fsm.sv:54|elevator_fsm.sv:34" *)  1'h0;
  assign _084_[0] = state[0] ^(* src = "elevator_fsm.sv:46|elevator_fsm.sv:34" *)  1'h0;
  assign _084_[1] = state[1] ^(* src = "elevator_fsm.sv:46|elevator_fsm.sv:34" *)  1'h1;
  assign _084_[2] = state[2] ^(* src = "elevator_fsm.sv:46|elevator_fsm.sv:34" *)  1'h0;
  assign _084_[3] = state[3] ^(* src = "elevator_fsm.sv:46|elevator_fsm.sv:34" *)  1'h0;
  assign _085_[0] = state[0] ^(* src = "elevator_fsm.sv:35|elevator_fsm.sv:34" *)  1'h1;
  assign _085_[1] = state[1] ^(* src = "elevator_fsm.sv:35|elevator_fsm.sv:34" *)  1'h0;
  assign _085_[2] = state[2] ^(* src = "elevator_fsm.sv:35|elevator_fsm.sv:34" *)  1'h0;
  assign _085_[3] = state[3] ^(* src = "elevator_fsm.sv:35|elevator_fsm.sv:34" *)  1'h0;
  assign _086_[0] = state[0] ^(* src = "elevator_fsm.sv:35|elevator_fsm.sv:34" *)  1'h1;
  assign _086_[1] = state[1] ^(* src = "elevator_fsm.sv:35|elevator_fsm.sv:34" *)  1'h0;
  assign _086_[2] = state[2] ^(* src = "elevator_fsm.sv:35|elevator_fsm.sv:34" *)  1'h0;
  assign _086_[3] = state[3] ^(* src = "elevator_fsm.sv:35|elevator_fsm.sv:34" *)  1'h0;
  assign _087_[0] = state[0] ^(* src = "elevator_fsm.sv:62|elevator_fsm.sv:34" *)  1'h0;
  assign _087_[1] = state[1] ^(* src = "elevator_fsm.sv:62|elevator_fsm.sv:34" *)  1'h0;
  assign _087_[2] = state[2] ^(* src = "elevator_fsm.sv:62|elevator_fsm.sv:34" *)  1'h0;
  assign _087_[3] = state[3] ^(* src = "elevator_fsm.sv:62|elevator_fsm.sv:34" *)  1'h1;
  assign _088_[0] = state[0] ^(* src = "elevator_fsm.sv:54|elevator_fsm.sv:34" *)  1'h0;
  assign _088_[1] = state[1] ^(* src = "elevator_fsm.sv:54|elevator_fsm.sv:34" *)  1'h0;
  assign _088_[2] = state[2] ^(* src = "elevator_fsm.sv:54|elevator_fsm.sv:34" *)  1'h1;
  assign _088_[3] = state[3] ^(* src = "elevator_fsm.sv:54|elevator_fsm.sv:34" *)  1'h0;
  assign _089_[0] = state[0] ^(* src = "elevator_fsm.sv:46|elevator_fsm.sv:34" *)  1'h0;
  assign _089_[1] = state[1] ^(* src = "elevator_fsm.sv:46|elevator_fsm.sv:34" *)  1'h1;
  assign _089_[2] = state[2] ^(* src = "elevator_fsm.sv:46|elevator_fsm.sv:34" *)  1'h0;
  assign _089_[3] = state[3] ^(* src = "elevator_fsm.sv:46|elevator_fsm.sv:34" *)  1'h0;
  assign _090_[0] = state[0] ^(* src = "elevator_fsm.sv:35|elevator_fsm.sv:34" *)  1'h1;
  assign _090_[1] = state[1] ^(* src = "elevator_fsm.sv:35|elevator_fsm.sv:34" *)  1'h0;
  assign _090_[2] = state[2] ^(* src = "elevator_fsm.sv:35|elevator_fsm.sv:34" *)  1'h0;
  assign _090_[3] = state[3] ^(* src = "elevator_fsm.sv:35|elevator_fsm.sv:34" *)  1'h0;
  assign _019_ = _016_ &(* src = "elevator_fsm.sv:33" *)  1'h1;
  assign _020_ = _015_ &(* src = "elevator_fsm.sv:33" *)  _019_;
  assign _017_ = _014_ &(* src = "elevator_fsm.sv:33" *)  _020_;
  assign _018_ = _013_ &(* src = "elevator_fsm.sv:33" *)  _017_;
  assign _160_[8] = 1'h0 &(* src = "elevator_fsm.sv:82|elevator_fsm.sv:68|<techmap.v>:434" *)  _120_;
  assign _160_[9] = 1'h1 &(* src = "elevator_fsm.sv:82|elevator_fsm.sv:68|<techmap.v>:434" *)  _120_;
  assign _160_[10] = 1'h0 &(* src = "elevator_fsm.sv:82|elevator_fsm.sv:68|<techmap.v>:434" *)  _120_;
  assign _160_[11] = 1'h1 &(* src = "elevator_fsm.sv:82|elevator_fsm.sv:68|<techmap.v>:434" *)  _120_;
  assign _160_[12] = 1'h0 &(* src = "elevator_fsm.sv:82|elevator_fsm.sv:68|<techmap.v>:434" *)  _120_;
  assign _160_[13] = 1'h0 &(* src = "elevator_fsm.sv:82|elevator_fsm.sv:68|<techmap.v>:434" *)  _120_;
  assign _160_[14] = 1'h0 &(* src = "elevator_fsm.sv:82|elevator_fsm.sv:68|<techmap.v>:434" *)  _120_;
  assign _160_[15] = 1'h0 &(* src = "elevator_fsm.sv:82|elevator_fsm.sv:68|<techmap.v>:434" *)  _120_;
  assign _160_[0] = _163_[0] &(* src = "elevator_fsm.sv:82|elevator_fsm.sv:68|<techmap.v>:434" *)  _162_;
  assign _160_[1] = _163_[1] &(* src = "elevator_fsm.sv:82|elevator_fsm.sv:68|<techmap.v>:434" *)  _162_;
  assign _160_[2] = _163_[2] &(* src = "elevator_fsm.sv:82|elevator_fsm.sv:68|<techmap.v>:434" *)  _162_;
  assign _160_[3] = _163_[3] &(* src = "elevator_fsm.sv:82|elevator_fsm.sv:68|<techmap.v>:434" *)  _162_;
  assign _160_[4] = _163_[4] &(* src = "elevator_fsm.sv:82|elevator_fsm.sv:68|<techmap.v>:434" *)  _162_;
  assign _160_[5] = _163_[5] &(* src = "elevator_fsm.sv:82|elevator_fsm.sv:68|<techmap.v>:434" *)  _162_;
  assign _160_[6] = _163_[6] &(* src = "elevator_fsm.sv:82|elevator_fsm.sv:68|<techmap.v>:434" *)  _162_;
  assign _160_[7] = _163_[7] &(* src = "elevator_fsm.sv:82|elevator_fsm.sv:68|<techmap.v>:434" *)  _162_;
  assign _121_[3] = 1'h0 &(* src = "elevator_fsm.sv:89|elevator_fsm.sv:68|<techmap.v>:434" *)  _126_;
  assign _121_[2] = 1'h0 &(* src = "elevator_fsm.sv:89|elevator_fsm.sv:68|<techmap.v>:434" *)  _125_;
  assign _121_[1] = 1'h0 &(* src = "elevator_fsm.sv:89|elevator_fsm.sv:68|<techmap.v>:434" *)  _124_;
  assign _121_[0] = 1'h0 &(* src = "elevator_fsm.sv:89|elevator_fsm.sv:68|<techmap.v>:434" *)  _123_;
  assign _127_[3] = 1'h0 &(* src = "elevator_fsm.sv:89|elevator_fsm.sv:68|<techmap.v>:434" *)  _132_;
  assign _127_[2] = 1'h0 &(* src = "elevator_fsm.sv:89|elevator_fsm.sv:68|<techmap.v>:434" *)  _131_;
  assign _127_[1] = 1'h0 &(* src = "elevator_fsm.sv:89|elevator_fsm.sv:68|<techmap.v>:434" *)  _130_;
  assign _127_[0] = 1'h0 &(* src = "elevator_fsm.sv:89|elevator_fsm.sv:68|<techmap.v>:434" *)  _129_;
  assign _133_[3] = 1'h1 &(* src = "elevator_fsm.sv:89|elevator_fsm.sv:68|<techmap.v>:434" *)  _138_;
  assign _133_[2] = 1'h0 &(* src = "elevator_fsm.sv:89|elevator_fsm.sv:68|<techmap.v>:434" *)  _137_;
  assign _133_[1] = 1'h0 &(* src = "elevator_fsm.sv:89|elevator_fsm.sv:68|<techmap.v>:434" *)  _136_;
  assign _133_[0] = 1'h1 &(* src = "elevator_fsm.sv:89|elevator_fsm.sv:68|<techmap.v>:434" *)  _135_;
  assign _139_[3] = 1'h0 &(* src = "elevator_fsm.sv:89|elevator_fsm.sv:68|<techmap.v>:434" *)  _144_;
  assign _139_[2] = 1'h1 &(* src = "elevator_fsm.sv:89|elevator_fsm.sv:68|<techmap.v>:434" *)  _143_;
  assign _139_[1] = 1'h1 &(* src = "elevator_fsm.sv:89|elevator_fsm.sv:68|<techmap.v>:434" *)  _142_;
  assign _139_[0] = 1'h0 &(* src = "elevator_fsm.sv:89|elevator_fsm.sv:68|<techmap.v>:434" *)  _141_;
  assign _154_[12] = _008_[0] &(* src = "elevator_fsm.sv:62|elevator_fsm.sv:34|<techmap.v>:434" *)  _159_;
  assign _154_[13] = _008_[1] &(* src = "elevator_fsm.sv:62|elevator_fsm.sv:34|<techmap.v>:434" *)  _159_;
  assign _154_[14] = _008_[2] &(* src = "elevator_fsm.sv:62|elevator_fsm.sv:34|<techmap.v>:434" *)  _159_;
  assign _154_[15] = _008_[3] &(* src = "elevator_fsm.sv:62|elevator_fsm.sv:34|<techmap.v>:434" *)  _159_;
  assign _154_[8] = _010_[0] &(* src = "elevator_fsm.sv:62|elevator_fsm.sv:34|<techmap.v>:434" *)  _158_;
  assign _154_[9] = _010_[1] &(* src = "elevator_fsm.sv:62|elevator_fsm.sv:34|<techmap.v>:434" *)  _158_;
  assign _154_[10] = _010_[2] &(* src = "elevator_fsm.sv:62|elevator_fsm.sv:34|<techmap.v>:434" *)  _158_;
  assign _154_[11] = _010_[3] &(* src = "elevator_fsm.sv:62|elevator_fsm.sv:34|<techmap.v>:434" *)  _158_;
  assign _154_[4] = _011_[0] &(* src = "elevator_fsm.sv:62|elevator_fsm.sv:34|<techmap.v>:434" *)  _157_;
  assign _154_[5] = _011_[1] &(* src = "elevator_fsm.sv:62|elevator_fsm.sv:34|<techmap.v>:434" *)  _157_;
  assign _154_[6] = _011_[2] &(* src = "elevator_fsm.sv:62|elevator_fsm.sv:34|<techmap.v>:434" *)  _157_;
  assign _154_[7] = _011_[3] &(* src = "elevator_fsm.sv:62|elevator_fsm.sv:34|<techmap.v>:434" *)  _157_;
  assign _154_[0] = 1'h1 &(* src = "elevator_fsm.sv:62|elevator_fsm.sv:34|<techmap.v>:434" *)  _156_;
  assign _154_[1] = 1'h0 &(* src = "elevator_fsm.sv:62|elevator_fsm.sv:34|<techmap.v>:434" *)  _156_;
  assign _154_[2] = 1'h0 &(* src = "elevator_fsm.sv:62|elevator_fsm.sv:34|<techmap.v>:434" *)  _156_;
  assign _154_[3] = 1'h0 &(* src = "elevator_fsm.sv:62|elevator_fsm.sv:34|<techmap.v>:434" *)  _156_;
  assign _163_[0] = _172_[0] ^(* src = "elevator_fsm.sv:87|<techmap.v>:263" *)  1'h1;
  assign _163_[1] = _173_[1] ^(* src = "elevator_fsm.sv:87|<techmap.v>:263" *)  _171_[0];
  assign _163_[2] = _173_[2] ^(* src = "elevator_fsm.sv:87|<techmap.v>:263" *)  _171_[1];
  assign _163_[3] = _173_[3] ^(* src = "elevator_fsm.sv:87|<techmap.v>:263" *)  _171_[2];
  assign _163_[4] = _173_[4] ^(* src = "elevator_fsm.sv:87|<techmap.v>:263" *)  _171_[3];
  assign _163_[5] = _173_[5] ^(* src = "elevator_fsm.sv:87|<techmap.v>:263" *)  _171_[4];
  assign _163_[6] = _173_[6] ^(* src = "elevator_fsm.sv:87|<techmap.v>:263" *)  _171_[5];
  assign _163_[7] = _173_[7] ^(* src = "elevator_fsm.sv:87|<techmap.v>:263" *)  _171_[6];
  assign _172_[0] = door_close_timer[0] ^(* src = "elevator_fsm.sv:87|<techmap.v>:262" *)  _170_[0];
  assign _173_[1] = door_close_timer[1] ^(* src = "elevator_fsm.sv:87|<techmap.v>:262" *)  _170_[1];
  assign _173_[2] = door_close_timer[2] ^(* src = "elevator_fsm.sv:87|<techmap.v>:262" *)  _170_[2];
  assign _173_[3] = door_close_timer[3] ^(* src = "elevator_fsm.sv:87|<techmap.v>:262" *)  _170_[3];
  assign _173_[4] = door_close_timer[4] ^(* src = "elevator_fsm.sv:87|<techmap.v>:262" *)  _170_[4];
  assign _173_[5] = door_close_timer[5] ^(* src = "elevator_fsm.sv:87|<techmap.v>:262" *)  _170_[5];
  assign _173_[6] = door_close_timer[6] ^(* src = "elevator_fsm.sv:87|<techmap.v>:262" *)  _170_[6];
  assign _173_[7] = door_close_timer[7] ^(* src = "elevator_fsm.sv:87|<techmap.v>:262" *)  _170_[7];
  assign _174_[0] = door_close_timer[0] &(* src = "elevator_fsm.sv:87|<techmap.v>:260" *)  _170_[0];
  assign _174_[1] = door_close_timer[1] &(* src = "elevator_fsm.sv:87|<techmap.v>:260" *)  _170_[1];
  assign _174_[2] = door_close_timer[2] &(* src = "elevator_fsm.sv:87|<techmap.v>:260" *)  _170_[2];
  assign _174_[3] = door_close_timer[3] &(* src = "elevator_fsm.sv:87|<techmap.v>:260" *)  _170_[3];
  assign _174_[4] = door_close_timer[4] &(* src = "elevator_fsm.sv:87|<techmap.v>:260" *)  _170_[4];
  assign _174_[5] = door_close_timer[5] &(* src = "elevator_fsm.sv:87|<techmap.v>:260" *)  _170_[5];
  assign _174_[6] = door_close_timer[6] &(* src = "elevator_fsm.sv:87|<techmap.v>:260" *)  _170_[6];
  assign _173_[0] = _172_[0];
endmodule
